### ISSUE TITLE
Configure renovate to automatically update the injected image

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-infra-operator#167]
## Summary

The image we inject as a sidecar is declared in the `values.yaml` file:
```yaml
config:
  infraAgentInjection:
    agentConfig:
      image:
        repository: newrelic/infrastructure-k8s
        tag: 2.10.0-unprivileged
        pullPolicy: IfNotPresent
```

## Desired Behavior

Renovatebot could try to parse these files and open PRs updating this automatically in the same way it is done e.g. in the infra bundle repository: https://github.com/newrelic/infrastructure-bundle/blob/master/.github/renovate.json5
