### ISSUE TITLE
Sidecar trying to be injected into "newrelic-kube-state-metrics" but failing

### ISSUE THREAD

**Issue by OliverRC** [newrelic/newrelic-infra-operator#234]
## Description

I removed the pod for `newrelic-kube-state-metrics`, and the deployment spun up a new one.
However, now the operator has injected the `newrelic-infrastructure-sidecar` which is not starting up, therefore causing the `newrelic-kube-state-metrics` to not start properly.

What is strange to me is that the operator configuration includes values that indicate it should not be injected.

## Steps to Reproduce

1. Install the EKS Fargate integration (https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/install-fargate-integration/)
2. Remove the `newrelic-kube-state-metrics` pod to allow a new pod to spin up post the operator installation

## Expected Behavior

Either
1. The sidecar should startup properly and therefore monitor `newrelic-kube-state-metrics`
2. or, `newrelic-kube-state-metrics` must be excluded from injection.

## Relevant Logs / Console output

No logs are found for the `newrelic-infrastructure-sidecar` container.

Error from side-car in `newrelic-kube-state-metrics` pod

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "30000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podfc387228-33b0-4eac-bb8b-e7d9945dbb03/newrelic-infrastructure-sidecar/cpu.cfs_quota_us: invalid argument: unknown
```

### Operator Config

```
ignoreMutationErrors: true
infraAgentInjection:
  agentConfig:
    configSelectors:
    - extraEnvVars:
        DISABLE_KUBE_STATE_METRICS: "true"
      labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
          - kube-state-metrics
        - key: app
          operator: NotIn
          values:
          - kube-state-metrics
        - key: k8s-app
          operator: NotIn
          values:
          - kube-state-metrics
      resourceRequirements:
        limits:
          cpu: 200m
          memory: 100M
        requests:
          cpu: 100m
          memory: 50M
    - labelSelector:
        matchLabels:
          k8s-app: kube-state-metrics
      resourceRequirements:
        limits:
          cpu: 300m
          memory: 300M
        requests:
          cpu: 150m
          memory: 150M
    - labelSelector:
        matchLabels:
          app: kube-state-metrics
      resourceRequirements:
        limits:
          cpu: 300m
          memory: 300M
        requests:
          cpu: 150m
          memory: 150M
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: kube-state-metrics
      resourceRequirements:
        limits:
          cpu: 300m
          memory: 300M
        requests:
          cpu: 150m
          memory: 150M
    customAttributes:
    - defaultValue: serverless
      name: computeType
    - fromLabel: eks.amazonaws.com/fargate-profile
      name: fargateProfile
    image:
      pullPolicy: IfNotPresent
      repository: newrelic/infrastructure-k8s
      tag: 2.13.5-unprivileged
  policies:
  - podSelector:
      matchExpressions:
      - key: eks.amazonaws.com/fargate-profile
        operator: Exists
  resourcePrefix: newrelic-newrelic-infra-operator
```

## Your Environment

* EKS with Fargate only
